Default: &defaults
  database: YesodAndGHCJSExample.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: YesodAndGHCJSExample_test.sqlite3
  <<: *defaults

Staging:
  database: YesodAndGHCJSExample_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: YesodAndGHCJSExample_production.sqlite3
  poolsize: 100
  <<: *defaults
